export enum TestExportType {
  QUESTION_PAPER = 'QUESTION_PAPER',
  ANSWER_KEY = 'ANSWER_KEY',
}
export enum TestExportStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED',
}
export enum TestRenderMode {
  QUESTION_PAPER = 'QUESTION_PAPER',
  ANSWER_KEY = 'ANSWER_KEY',
}
export enum TestExportErrorCode {
  TEST_NOT_FINALIZED = 'TEST_NOT_FINALIZED',
  TEST_EXPORT_NOT_FOUND = 'TEST_EXPORT_NOT_FOUND',
  TEST_EXPORT_ACCESS_DENIED = 'TEST_EXPORT_ACCESS_DENIED',
  TEST_EXPORT_ALREADY_PROCESSING = 'TEST_EXPORT_ALREADY_PROCESSING',
  PDF_RENDER_FAILED = 'PDF_RENDER_FAILED',
  PDF_STORAGE_FAILED = 'PDF_STORAGE_FAILED',
  PDF_INVALID_OUTPUT = 'PDF_INVALID_OUTPUT',
  PDF_EXPORT_LIMIT_EXCEEDED = 'PDF_EXPORT_LIMIT_EXCEEDED',
  PDF_EXPORT_PROVIDER_ERROR = 'PDF_EXPORT_PROVIDER_ERROR',
}
