export enum EmbeddingStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  STALE = 'STALE',
}

export enum EmbeddingJobStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  PARTIAL = 'PARTIAL',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum EmbeddingErrorCode {
  AUTH_FAILED = 'EMBEDDING_AUTH_FAILED',
  RATE_LIMITED = 'EMBEDDING_RATE_LIMITED',
  TIMEOUT = 'EMBEDDING_TIMEOUT',
  MODEL_NOT_FOUND = 'EMBEDDING_MODEL_NOT_FOUND',
  INPUT_TOO_LARGE = 'EMBEDDING_INPUT_TOO_LARGE',
  PROVIDER_ERROR = 'EMBEDDING_PROVIDER_ERROR',
  RESPONSE_MISMATCH = 'EMBEDDING_RESPONSE_MISMATCH',
  DIMENSION_MISMATCH = 'EMBEDDING_DIMENSION_MISMATCH',
  PROVIDER_NOT_CONFIGURED = 'EMBEDDING_PROVIDER_NOT_CONFIGURED',
}
