export enum TenantScope {
  GLOBAL = 'GLOBAL',
  SCHOOL = 'SCHOOL',
}
export enum KnowledgeDocumentStatus {
  DRAFT = 'DRAFT',
  PROCESSING = 'PROCESSING',
  READY_FOR_REVIEW = 'READY_FOR_REVIEW',
  READY_FOR_MAPPING = 'READY_FOR_MAPPING',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED',
}
export enum KnowledgeSourceType {
  PDF = 'PDF',
  DOCX = 'DOCX',
  TXT = 'TXT',
  ADMIN_NOTE = 'ADMIN_NOTE',
}
export enum ExtractionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
export enum MalwareScanStatus {
  NOT_SCANNED = 'NOT_SCANNED',
  PENDING = 'PENDING',
  SCANNING = 'SCANNING',
  CLEAN = 'CLEAN',
  INFECTED = 'INFECTED',
  FAILED = 'FAILED',
}
export enum MappingStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
}
export enum MappingSpecificity {
  BOARD = 1,
  CLASS = 2,
  SUBJECT = 3,
  CHAPTER = 4,
  TOPIC = 5,
}
export enum ReadinessBlocker {
  EXTRACTION_NOT_COMPLETE = 'EXTRACTION_NOT_COMPLETE',
  COMPLETENESS_NOT_VERIFIED = 'COMPLETENESS_NOT_VERIFIED',
  NO_CONTENT_CHUNKS = 'NO_CONTENT_CHUNKS',
  NO_CURRICULUM_MAPPING = 'NO_CURRICULUM_MAPPING',
  MAPPING_PENDING_APPROVAL = 'MAPPING_PENDING_APPROVAL',
  RIGHTS_NOT_CONFIRMED = 'RIGHTS_NOT_CONFIRMED',
  DOCUMENT_ARCHIVED = 'DOCUMENT_ARCHIVED',
  VERSION_ARCHIVED = 'VERSION_ARCHIVED',
  CURRICULUM_ARCHIVED = 'CURRICULUM_ARCHIVED',
  MALWARE_NOT_SCANNED = 'MALWARE_NOT_SCANNED',
  MALWARE_SCAN_FAILED = 'MALWARE_SCAN_FAILED',
  MALWARE_DETECTED = 'MALWARE_DETECTED',
  EMBEDDINGS_MISSING = 'EMBEDDINGS_MISSING',
  EMBEDDING_PROVIDER_NOT_CONFIGURED = 'EMBEDDING_PROVIDER_NOT_CONFIGURED',
  EMBEDDINGS_PARTIAL = 'EMBEDDINGS_PARTIAL',
  EMBEDDINGS_FAILED = 'EMBEDDINGS_FAILED',
  EMBEDDINGS_STALE = 'EMBEDDINGS_STALE',
  EMBEDDING_CONFIG_MISMATCH = 'EMBEDDING_CONFIG_MISMATCH',
  OCR_REQUIRED = 'OCR_REQUIRED',
  OCR_INCOMPLETE = 'OCR_INCOMPLETE',
}
