export enum NotificationType {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  AI_GENERATION_COMPLETED = 'AI_GENERATION_COMPLETED',
  AI_GENERATION_FAILED = 'AI_GENERATION_FAILED',
  TEST_FINALIZED = 'TEST_FINALIZED',
  PDF_EXPORT_COMPLETED = 'PDF_EXPORT_COMPLETED',
  PDF_EXPORT_FAILED = 'PDF_EXPORT_FAILED',
  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_PAYMENT_SUCCEEDED = 'SUBSCRIPTION_PAYMENT_SUCCEEDED',
  SUBSCRIPTION_PAYMENT_FAILED = 'SUBSCRIPTION_PAYMENT_FAILED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SYSTEM = 'SYSTEM',
}
export enum DeliveryStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
export const MANDATORY_EMAIL_TYPES = new Set([
  NotificationType.EMAIL_VERIFICATION,
  NotificationType.PASSWORD_RESET,
  NotificationType.PASSWORD_CHANGED,
]);
