export enum BillingInterval {
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
}
export enum SubscriptionStatus {
  TRIALING = 'TRIALING',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
export enum UsageMetric {
  AI_QUESTIONS = 'AI_QUESTIONS',
  TESTS = 'TESTS',
  PDF_EXPORTS = 'PDF_EXPORTS',
  STORAGE_BYTES = 'STORAGE_BYTES',
}
export enum ReservationStatus {
  ACTIVE = 'ACTIVE',
  PARTIALLY_SETTLED = 'PARTIALLY_SETTLED',
  SETTLED = 'SETTLED',
  RELEASED = 'RELEASED',
  EXPIRED = 'EXPIRED',
}
export enum UsageEventType {
  RESERVE = 'RESERVE',
  SETTLE = 'SETTLE',
  RELEASE = 'RELEASE',
  EXPIRE = 'EXPIRE',
  ADJUST = 'ADJUST',
}
export enum EntitlementErrorCode {
  NO_ACTIVE_SUBSCRIPTION = 'NO_ACTIVE_SUBSCRIPTION',
  PLAN_INACTIVE = 'PLAN_INACTIVE',
  SUBSCRIPTION_INACTIVE = 'SUBSCRIPTION_INACTIVE',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  USAGE_LIMIT_EXCEEDED = 'USAGE_LIMIT_EXCEEDED',
  INVALID_BILLING_PERIOD = 'INVALID_BILLING_PERIOD',
  ENTITLEMENT_CONFIGURATION_ERROR = 'ENTITLEMENT_CONFIGURATION_ERROR',
}
