export enum IngestionJobStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  AWAITING_MAPPING = 'AWAITING_MAPPING',
}
export enum IngestionStep {
  UPLOAD_RECEIVED = 'UPLOAD_RECEIVED',
  QUARANTINED = 'QUARANTINED',
  SIGNATURE_VALIDATION = 'SIGNATURE_VALIDATION',
  MALWARE_SCAN = 'MALWARE_SCAN',
  TEXT_EXTRACTION = 'TEXT_EXTRACTION',
  OCR = 'OCR',
  NORMALIZATION = 'NORMALIZATION',
  CHUNKING = 'CHUNKING',
  EMBEDDING = 'EMBEDDING',
  MAPPING = 'MAPPING',
  VERIFICATION = 'VERIFICATION',
  READY_FOR_MAPPING = 'READY_FOR_MAPPING',
  READY_FOR_REVIEW = 'READY_FOR_REVIEW',
}
