export enum GenerationJobStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  PARTIAL = 'PARTIAL',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
export enum GenerationItemStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  INSUFFICIENT_KNOWLEDGE = 'INSUFFICIENT_KNOWLEDGE',
}
export enum GroundingMode {
  REQUIRED = 'REQUIRED',
  PREFERRED = 'PREFERRED',
}
export enum AiErrorCode {
  PROVIDER_NOT_CONFIGURED = 'AI_PROVIDER_NOT_CONFIGURED',
  AUTH_FAILED = 'AI_AUTH_FAILED',
  MODEL_NOT_FOUND = 'AI_MODEL_NOT_FOUND',
  TIMEOUT = 'AI_TIMEOUT',
  RATE_LIMITED = 'AI_RATE_LIMITED',
  PROVIDER_ERROR = 'AI_PROVIDER_ERROR',
  OUTPUT_TRUNCATED = 'AI_OUTPUT_TRUNCATED',
  INVALID_RESPONSE = 'AI_INVALID_RESPONSE',
  SCHEMA_VALIDATION_FAILED = 'AI_SCHEMA_VALIDATION_FAILED',
  CITATION_VALIDATION_FAILED = 'AI_CITATION_VALIDATION_FAILED',
  DUPLICATE_REJECTED = 'AI_DUPLICATE_REJECTED',
  COUNT_MISMATCH = 'AI_COUNT_MISMATCH',
  INSUFFICIENT_KNOWLEDGE = 'INSUFFICIENT_KNOWLEDGE',
  CANCELLED = 'AI_JOB_CANCELLED',
}
